# Generated by Django 5.2.10 on 2026-02-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
