# Generated by Django 5.2.10 on 2026-02-03 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_tag_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Tell Django the field exists without running SQL (field already in database)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='repository',
                    name='pull_count',
                    field=models.IntegerField(default=0),
                ),
            ],
            database_operations=[
                # No SQL to execute - field already exists
            ],
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['visibility', '-pull_count'], name='repo_vis_pull_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['visibility', '-updated_at'], name='repo_vis_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['is_official'], name='repo_official_idx'),
        ),
        migrations.AddIndex(
            model_name='star',
            index=models.Index(fields=['repository'], name='star_repo_idx'),
        ),
        migrations.AddIndex(
            model_name='star',
            index=models.Index(fields=['user', 'repository'], name='star_user_repo_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['repository', '-created_at'], name='tag_repo_date_idx'),
        ),
    ]
