# Generated by Django 5.2.10 on 2026-02-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_repository_pull_count_alter_repository_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='star_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
